let enemiesData = [
    {
        "id":"0",
        "f_name":"Rajing",
        "s_name":"Rooper",
        "enemy_img":"img/Rajing.jpg",
        "enemy_img_big":"img/Rajing-Rooper.jpg",
        "enemy_lvl":"1",
        "enemy_dmg":"Dmg:5",
        "enemy_def":"Def:3",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:100",
        "enemy_ab1":"tnrnfxhn",
        "enemy_ab2":"nfgfnhn",
        "enemy_descr":"A northern warrior who is somewhat human-like. He wields a magic staff like a stick.",
        "enemy_gold":"Gold:10",
        "css_class":"Rajing-Rooper"
    },
    {
        "id":"1",
        "f_name":"Stobb",
        "s_name":"Winston",
        "enemy_img":"img/Stobb.jpg",
        "enemy_img_big":"img/Stobb-Winston.jpg",
        "enemy_lvl":"2",
        "enemy_dmg":"Dmg:5",
        "enemy_def":"Def:2",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:250",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A healer magician who has the ability to heal. Apparently he doesn't heal well, since his magic poisons enemies.",
        "enemy_gold":"Gold:20",
        "css_class":"Stobb-Winston"
    },    {
        "id":"2",
        "f_name":"Hermit",
        "s_name":"",
        "enemy_img":"img/Hermit.jpg",
        "enemy_img_big":"img/Hermit1.jpg",
        "enemy_lvl":"3",
        "enemy_dmg":"Dmg:10",
        "enemy_def":"Def:3",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:200",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A mighty hermit with bull horns, armor and dyed blue hair. It’s better to remain silent about hair.",
        "enemy_gold":"Gold:30",
        "css_class":"Hermit1"
    },    {
        "id":"3",
        "f_name":"Loomys",
        "s_name":"Devil",
        "enemy_img":"img/Loomys.jpg",
        "enemy_img_big":"img/Loomys-Devil.jpg",
        "enemy_lvl":"4",
        "enemy_dmg":"Dmg:10",
        "enemy_def":"Def:2",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:100",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A terrible lizard demon with scales, bull horns and bat wings. Judging by the belly, it may be a female.",
        "enemy_gold":"Gold:30",
        "css_class":"Loomys-Devil"
    },    {
        "id":"4",
        "f_name":"Jeivzz",
        "s_name":"Rockfeller",
        "enemy_img":"img/Jeivzz.jpg",
        "enemy_img_big":"img/Jeivzz-Rockfeller.jpg",
        "enemy_lvl":"5",
        "enemy_dmg":"Dmg:6",
        "enemy_def":"Def:10",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:200",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A powerful knight, capable of defeating anyone who gets in his way. He forgot his sword at home.",
        "enemy_gold":"Gold:40",
        "css_class":"Jeivzz-Rockfeller"
    },    {
        "id":"5",
        "f_name":"Morro",
        "s_name":"Lanister",
        "enemy_img":"img/Morro.jpg",
        "enemy_img_big":"img/Morro-Lanister.jpg",
        "enemy_lvl":"6",
        "enemy_dmg":"Dmg:2",
        "enemy_def":"Def:3",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:200",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A necromancer magician who wields the dark forces of the undead. Skeletons are his pets.",
        "enemy_gold":"Gold:45",
        "css_class":"Morro-Lanister"
    },    {
        "id":"6",
        "f_name":"Rango",
        "s_name":"Fearless",
        "enemy_img":"img/Rango.jpg",
        "enemy_img_big":"img/Rango-Fearless.jpg",
        "enemy_lvl":"7",
        "enemy_dmg":"Dmg:30",
        "enemy_def":"Def:10",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:500",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"A crazy monster ready to tear you to pieces with its physical strength. He would become the best bodybuilder.",
        "enemy_gold":"Gold:45",
        "css_class":"Rango-Fearless"
    },    {
        "id":"7",
        "f_name":"Qweezly",
        "s_name":"Robinson",
        "enemy_img":"img/Qweezly.jpg",
        "enemy_img_big":"img/Qweezly-Robinson.jpg",
        "enemy_lvl":"8",
        "enemy_dmg":"Dmg:20",
        "enemy_def":"Def:20",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:100",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"The strongest of the satyrs, wielding the power of shadows.",
        "enemy_gold":"Gold:50",
        "css_class":"Qweezly-Robinson"
    },    {
        "id":"8",
        "f_name":"Hozuki",
        "s_name":"Heartless",
        "enemy_img":"img/Hozuki.jpg",
        "enemy_img_big":"img/Hozuki-Heartless.jpg",
        "enemy_lvl":"9",
        "enemy_dmg":"Dmg:100",
        "enemy_def":"Def:15",
        "enemy_exp":"Exp:10",
        "enemy_hp":"HP:400",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"He masters the ancient art of swordsmanship, the best of the samurai.",
        "enemy_gold":"Gold:100",
        "css_class":"Hozuki-Heartless"
    },    {
        "id":"9",
        "f_name":"Mad",
        "s_name":"Morton",
        "enemy_img":"img/Mad.jpg",
        "enemy_img_big":"img/Mad-Morton.jpg",
        "enemy_lvl":"10",
        "enemy_dmg":"Dmg:50",
        "enemy_def":"Def:",
        "enemy_exp":"",
        "enemy_hp":"HP:1000",
        "enemy_ab1":"",
        "enemy_ab2":"",
        "enemy_descr":"The mad lord of fire, the strongest of all creatures. Unlike humans, it consists of 80 percent fire.",
        "enemy_gold":"Gold:",
        "css_class":"Mad-Morton"
    },
]